version: '2'
services:
  server:
     image: pibot/gocd-server
     build:
       context: ./gocd/server/
       dockerfile: Dockerfile
     ports:
       - 80:8153
       - 443:8154
  node-agent:
      image: node-agent
      build:
        context: ./gocd/node-agent/
        dockerfile: Dockerfile
      links:
        - server
