version: '2'
services:
  server:
    image: registry.ng.bluemix.net/mobcontainers/bci-gocd-server:0.0.6
    build:
      context: ./gocd/server/
      dockerfile: Dockerfile
    ports:
      - 80:8153
      - 443:8154
  agent:
    image: openjdk
    build:
      context: ./gocd/agent/
      dockerfile: Dockerfile
    links:
      - server
  pythonagent:
    image: openjdk
    build:
      context: ./gocd/pythonAgent/
      dockerfile: Dockerfile
    links:
      - server
